# This is a TOML document.
# basic ip = lapla
# seocnd ec2_ip  = ip

[Servers]
number = 1
    [Servers.0]
    ipv4 = '156.216.102.122'

[Basic]
parent = 0
model = '1eR8_1X5erBkVlliRDGa_q-0SCmegwTxc'
redownload = 0
label = 'basic.txt'
shape = 23

[Second]
    [Second.0]
    parent = 0
    model = '1TDOD0169iEs-nvpNce00qOpleiUzUB-n'
    redownload = 0
    shape = 8

    [Second.19]
    parent = 0
    model = '1dH9RYHz9cY59oUfPSwHVRBrWDVAah_Yy'
    redownload = 0
    shape = 7

    [Second.2]
    parent = 0
    model = '1nDAjEVHz0YcQNpBW_g75lC2S4ZXwh_-W'
    redownload = 0
    shape = 7

