# This is a TOML document.
# basic ip = lapla
# seocnd ec2_ip  = ip

[Servers]
number = 1
    [Servers.0]
    ipv4 = '156.216.102.122'

[Basic]
parent = 0
model = '1eR8_1X5erBkVlliRDGa_q-0SCmegwTxc'

[Second]
    [Second.0]
    parent = 0
    model = '1TDOD0169iEs-nvpNce00qOpleiUzUB-n'

    [Second.1]
    parent = 0
    model = '1dH9RYHz9cY59oUfPSwHVRBrWDVAah_Yy'

    [Second.2]
    parent = 0
    model = '1nDAjEVHz0YcQNpBW_g75lC2S4ZXwh_-W'

    [Second.3]
    parent =0
    model = "dad"